=== Ambaram/WeSupport/Data/Users/Users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="User" maxOccurs="unbounded" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Type">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Admin"></xs:enumeration>
                                        <xs:enumeration value="Client"></xs:enumeration>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Userid">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="TT[0-9]{5}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Name">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="First"></xs:element>
                                        <xs:element name="Last"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Password"></xs:element>
                            <xs:element name="Hashpassword"></xs:element>
                            <xs:element name="Country"></xs:element>
                            <xs:element name="Contact">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Email"></xs:element>
                                        <xs:element name="Phone"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Ambaram/WeSupport/Data/Users/Users.xml
<?xml version="1.0" encoding="UTF-8"?>
<Users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Users.xsd">
    <User>
        <Type>Admin</Type>
        <Userid>TT12345</Userid>
        <Name>
            <First>John</First>
            <Last>Smith</Last>
        </Name>
        <Password>12345</Password>
        <Hashpassword/>
        <Country>India</Country>
        <Contact>                                    <!-- Fields required for user login(email/contact no)-->
            <Email>john.smith@gmail.com</Email> 
            <Phone>0012343212</Phone>
        </Contact>
    </User>
    <User>
        <Type>Client</Type>
        <Userid>TT12334</Userid>
        <Name>
            <First>John</First>
            <Last>Doe</Last>
        </Name>
        <Password>122123</Password>
        <Hashpassword></Hashpassword><!-- Encrypted Password -->
        <Country>Canada </Country>
        <Contact>                                   <!-- Fields required for user login(email/contact no)-->
            <Email>john.doe@gmail.com</Email>
            <Phone>0012345312</Phone>
        </Contact>
    </User>
    <User>
        <Type>Client</Type>
        <Userid>TT68966</Userid>
        <Name>
            <First>Ambaram</First>
            <Last>Srivastava</Last>
        </Name>
        <Password>123</Password>
        <Hashpassword>202cb962ac59075b964b07152d234b70</Hashpassword>
        <Country/>
        <Contact>
            <Email>ambaramsrivastava@gmail.com</Email>
            <Phone>08865863361</Phone>
        </Contact>
    </User>
    <User>
        <Type>Client</Type>
        <Userid>TT41953</Userid>
        <Name>
            <First>Ambaram</First>
            <Last>Srivastava</Last>
        </Name>
        <Password>1234</Password>
        <Hashpassword>202cb962ac59075b964b07152d234b70</Hashpassword>
        <Country/>
        <Contact>
            <Email>ambaramsrivastava@gmail.com</Email>
            <Phone>08865863361</Phone>
        </Contact>
    </User>
</Users>
