=== Ambaram/WeSupport/Data/Tickets/Support_Tickets.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Tickets">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Ticket" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ID" minOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="TX[0-9][0-9][0-9][0-9][0-9]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Priority">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:enumeration value="1"></xs:enumeration>
                                        <xs:enumeration value="2"></xs:enumeration>
                                        <xs:enumeration value="3"></xs:enumeration>
                                        <xs:enumeration value="4"></xs:enumeration>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Client">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Name">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="First"></xs:element>
                                                    <xs:element name="Last"></xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Userid"></xs:element>
                                        <xs:element name="Email"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Subject" minOccurs="1"></xs:element>
                            <xs:element name="Description" minOccurs="1"></xs:element>
                            <xs:element name="State" minOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Created"></xs:enumeration>
                                        <xs:enumeration value="Assigned"></xs:enumeration>
                                        <xs:enumeration value="In Progress"></xs:enumeration>
                                        <xs:enumeration value="On Hold"></xs:enumeration>
                                        <xs:enumeration value="Resolved"></xs:enumeration>
                                        <xs:enumeration value="Closed"></xs:enumeration>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Admin">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Userid"></xs:element>
                                        <xs:element name="Email"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Timetracking">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Created" type="Timestamp"></xs:element>
                                        <xs:element name="Lastupdated" type="Timestamp"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Messages" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Message"></xs:element>
                                        <xs:element name="Timestamp"></xs:element>
                                        <xs:element name="Userid"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Timestamp">
        <xs:sequence>
            <xs:element name="Date"></xs:element>
            <xs:element name="Time"></xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Ambaram/WeSupport/Data/Tickets/Support_Tickets.xml
<?xml version="1.0" encoding="UTF-8"?>
<Tickets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Support_Tickets.xsd">
    <Ticket>
        <ID>TX43433</ID>
        <Priority>3</Priority>      <!--Priority out of (1/2/3/4)-->
        <Client>                    <!-- Caller Details -->
            <Name>
                <First>John</First>
                <Last>Doe</Last>
            </Name>
            <Userid>TT12334</Userid>
            <Email>john.doe@gmail.com</Email>
        </Client>          
        <Subject>Application Down</Subject>   
        <Description>
            While trying to open the application i am receiving error "Application exiting with error 5404!!"
        </Description>
        <State>Created</State>      <!--State out of (Created/Assigned/In Progress/On Hold/Resolved/Closed)-->
        <Admin>                <!-- Admin Details -->
            <Userid>TT12345</Userid>
            <Email>john.smith@gmail.com</Email>
        </Admin>
        <Timetracking>
            <Created>
                <Date>17-02-2021</Date>
                <Time>08:45:04</Time>
            </Created>
            <Lastupdated>
                <Date>18-02-2021</Date>
                <Time>09:21s:04</Time>
            </Lastupdated>
        </Timetracking>
        <Messages>                     <!--Client and admin chat box can contain multiple note-->
            <Message>Requested error screenshot from user</Message>
            <Timestamp>01/04/2021::01:22:40</Timestamp>
            <Userid>TT12345</Userid>        <!--Updates from user and assigned contact-->
        </Messages>                    
    </Ticket>
    <Ticket>
        <ID>TX23232</ID>
        <Priority>2</Priority>      <!--Priority out of (1/2/3/4)-->
        <Client>                    <!-- Caller Details -->
            <Name>
                <First>Ambaram</First>
                <Last>Srivastava</Last>
            </Name>
            <Userid>TT68966</Userid>
            <Email>ambaramsrivastava@gmail.com</Email>
        </Client>
        <Subject>Login Failed</Subject>
        <Description>
            "Login failure!! Could not login user at this time. Please contact system administrator"
        </Description>
        <State>In Progress</State>      <!--State out of (Created/Assigned/In Progress/On Hold/Resolved/Closed)-->
        <Admin>                <!-- Admin Details -->
            <Userid>TT12345</Userid>
            <Email>johnsmitch@gmail.com</Email>
        </Admin>
        <Timetracking>
            <Created>
                <Date>17-02-2021</Date>
                <Time>08:45:04</Time>
            </Created>
            <Lastupdated>
                <Date>18-02-2021</Date>
                <Time>09:21s:04</Time>
            </Lastupdated>
        </Timetracking>
        <Messages>                     <!--Client and admin chat box can contain multiple note-->
            <Message>Requested error screenshot from user</Message>
            <Timestamp>01/04/2021::01:22:40</Timestamp>
            <Userid>TT12345</Userid>        <!--Updates from user and assigned contact-->
        </Messages>
    </Ticket>
    <Ticket>
        <ID>TX45321</ID>
        <Priority>3</Priority>      <!--Priority out of (1/2/3/4)-->
        <Client>                    <!-- Caller Details -->
            <Name>
                <First>John</First>
                <Last>Doe</Last>
            </Name>
            <Userid>2</Userid>
            <Email>john.doe@gmail.com</Email>
        </Client>
        <Subject>Application Down</Subject>
        <Description>
            While trying to open the application i am receiving error "Application exiting with error 5404!!"
        </Description>
        <State>Created</State>      <!--State out of (Created/Assigned/In Progress/On Hold/Resolved/Closed)-->
        <Admin>                <!-- Admin Details -->
            <Userid>TT12345</Userid>
            <Email>john.smith@gmail.com</Email>
        </Admin>
        <Timetracking>
            <Created>
                <Date>17-02-2021</Date>
                <Time>08:45:04</Time>
            </Created>
            <Lastupdated>
                <Date>18-02-2021</Date>
                <Time>09:21s:04</Time>
            </Lastupdated>
        </Timetracking>
        <Messages>                     <!--Client and admin chat box can contain multiple note-->
            <Message>Requested error screenshot from user</Message>
            <Timestamp>01/04/2021::01:22:40</Timestamp>
            <Userid>1/2</Userid>        <!--Updates from user and assigned contact-->
        </Messages>
    </Ticket>
</Tickets>
